services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge
