export const HttpResponse = {
    SERVER_ERROR : 'Inter server Error',
    USER_EXIST : 'User already exist',
    PAGE_NOT_FOUND : 'Page Not Found',
    USER_NOT_FOUND : 'User Not Found',
    INVALID_CREDENTIALS : 'Invalid Credentials',
    NO_TOKEN : "Token Not Provided",
    OTP_INCORRECT : 'Incorrect OTP , try again',
    OTP_EXPIRED : "OTP Expired , Please Resend OTP",
    CREATED : 'Created Successfully',
    USER_CREATION_FAILED : 'User Creation Failed',
    TOKEN_EXPIRED :'Token Expired',
    RESET_LINK_SEND :'Reset Password Sended To your Email , Check Your Mail',
    RESET_PASS_FAILED : 'Reset Password Failed',
    RESET_PASS_SUCCESS : 'Password Resetted Succesfully',
    IMAGE_NOT_PROVIDED : 'Please Provide a Image to upload',
    UPDATED : 'Updated Successfully',
    OLD_PASS_NOT_MATCHED : 'Old Password you provided is incorrect , Try another one',
    USER_BLOCKED : 'You are Blocked By admin',
    ADDED_TO_GROUP :"Added To Group",
    LEFT_GROUP : 'Left From group',
    RESOURCE_NOT_FOUND  :'Resource not found'
}